### ISSUE TITLE
how to ota

### ISSUE THREAD

**Issue by WangChun420** [feanor-anglin/GetWired-Project#21]
I see the define MY_OTA_FIRMWARE_FEATURE - enables firmware-over-the-wire updates (defined by default)，but how to?is there use some other bootloader?

**Comment by feanor-anglin** [comment]
We have not yet documented this feature on our wiki, because it is not entirely ready. It is possible, though there is a bootloader problem - code has to be compiled for Sensebender Micro hardware package for Arduino IDE, and Dualoptiboot bootloader has to be used. But, you won't be able to flash firmware to MCU with this settings, you will have to use AVRDUDE. Also, have a look at [this article](https://www.mysensors.org/about/fota).
